server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/nnt_project1
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        database: postgresql
        enable_lazy_load_no_trans: true
  sql:
    init:
      mode: never

# Enable Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# CORS configuration
cors:
  allowed-origins: http://localhost:3000
